title: Evan Tan
# profile links
accounts:
    github: evantancy
    linkedin: evantancy
    twitter: nat_nave
    stackoverflow: 13351062
    kaggle: evantancy

url: evantancy.github.io
paths:
    resume: "/assets/EvanTan-Resume.pdf"

markdown: kramdown
highlighter: rouge
# account for GMT +8
# future: true

collections:
    projects:
        output: true
        permalink: /:collection/:path
    posts:
        output: true
        permalink: /blog/:path

kramdown:
    math_engine: katex
    syntax_highlighter_opts:
        block:
            line_numbers: true

sass:
    sass_dir: css
    style: compressed

katex:
    js_path: assets/katex/ # Path used to search for katex.min.js
    rendering_options:
        # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
        throw_error: true # throwOnError - set to false if you want rendering to output error as text rather than a build error
        error_color: "#cc0000" # errorColor

plugins:
    - jekyll-katex
    - jekyll-scholar
    - jekyll-target-blank
