markdown: kramdown

# profile links
accounts:
  github: evan-tan

collections:
  projects:
    output: true
    permalink: /projects/:path/

kramdown:
  math_engine: katex

katex:
  js_path: "/assets/katex/" # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000" # errorColor
